name: ldm
channels:
  - pytorch
  - defaults
  - nvidia
dependencies:
  - python=3.10
  - pip
  - nvidia/label/cuda-12.4.0::cuda-toolkit  # Specify CUDA 12.4.0 from NVIDIA channel
  - pip:
    # - --extra-index-url https://download.pytorch.org/whl/cu124 
    - albumentations
    - opencv-python
    - pudb==2019.2
    - torch==2.4.0
    - torchvision==0.19.0
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - pytorch-lightning==2.4.0
    - omegaconf==2.1.1
    - test-tube>=0.7.5
    - streamlit>=0.73.1
    - einops
    - torch-fidelity==0.3.0
    - transformers
    - monai
    - timm
    - nibabel
    - scikit-learn
    - python-dotenv
    - comet-ml>=3.31.0
    - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
    - -e git+https://github.com/openai/CLIP.git@main#egg=clip
    - git+https://github.com/Dao-AILab/flash-attention.git
    - -e .