model:
  base_learning_rate: 4e-4
  target: ldm.modules.vitvq3d.models.vitae.Vit_Seg_Trainer
  params:
    # modalities: ['t1', 't1ce', 't2', 'flair']
    # ckpt_path: ./weights/last.ckpt # to be filled
    monitor: val/dice_loss
    activation_fn: 'softmax'
    to_one_hot: True
    modelconfig:
      target: ldm.models.swinunet.swlinunetr.SwinUNETR
      params: 
        in_channels: 1
        feature_size: 48
        img_size: [96, 96, 96]
        # window_size: [7, 7, 7]
        # patch_size: [2, 2, 2]
        # depths: [2, 2, 2]
        # num_heads: [ 3, 6, 12, 24 ] 
        # drop_path_rate: 0.2
        out_channels: 14
        use_checkpoint: False
        use_flash: True
        # use_wlin: 125
    lossconfig:
      target: monai.losses.DiceLoss
      params:
        to_onehot_y: True
        softmax: True
    metricconfig:
      target: monai.metrics.DiceMetric
      params:
        include_background: True
        get_not_nans: True
        reduction: mean_batch
    # first_stage_weights: ./logs/2024-09-09T21-24-50_autoencoder_vitgan_xs_cloud/checkpoints/epoch=000075.ckpt
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 2
    num_workers: 16
    wrap: false
    # sampler_cls: ldm.data.btcv_monai.Sampler
    train:
      target: ldm.data.btcv_monai.BTCVSegTrainDataset
      params:
        json_list: btcv_fold_1.json # to be filled
        data_dir: /root/datasets/RawData/Training/
        repeat: 20
    validation:
      target: ldm.data.btcv_monai.BTCVSegValDataset
      params:
        json_list: btcv_fold_1.json # to be filled
        data_dir: /root/datasets/RawData/Training/
        

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 40
        max_images: 8
        increase_log_steps: False
        rescale: False
  trainer:
    benchmark: True
    precision: bf16-mixed
    max_epochs: 250
    devices: 0,1,2
    check_val_every_n_epoch: 5
    log_every_n_steps: 40
    # num_sanity_val_steps: 0
