model:
  base_learning_rate: 4.5e-6
  target: ldm.models.autoencoder.VQModel3D
  params:
    # modalities: ['t1', 't1ce', 't2', 'flair']
    # ckpt_path: ./weights/last.ckpt # to be filled
    embed_dim: 3
    n_embed: 8192
    ddconfig:
      double_z: False
      z_channels: 3
      resolution: 192 
      in_channels: 1
      out_ch: 1
      ch: 128
      ch_mult:
      - 1
      - 1
      - 2
      num_res_blocks: 2
      attn_resolutions: [8]
      dropout: 0.0
    lossconfig:
      target: ldm.modules.losses.vqperceptual.VQLPIPS3DWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 1
        disc_start: 10000
        disc_weight: 0.8
        codebook_weight: 1.0
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 8
    wrap: false
    train:
      target: ldm.data.brats.BratsDataset
      params:
        data_path: D:\Datasets\BraTS2020\BraTS2020_TrainingData\MICCAI_BraTS2020_TrainingData # to be filled
        crop_size: #h,w,d
          - 80
          - 80
          - 60
    validation:
      target: ldm.data.brats.BratsDataset
      params:
        data_path: D:\Datasets\BraTS2020\BraTS2020_ValidationData\MICCAI_BraTS2020_ValidationData # to be filled
        crop_size: #h,w,d
          - 80
          - 80
          - 60

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: False
        rescale: False

  trainer:
    benchmark: True
